---

stages:
    - build
    - security

variables:
    MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
    MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
    
include:
    - remote: 'https://gitlab.com/verademo/security-ci-includes/-/blob/master/sast-scan.yml'
    - remote: 'https://gitlab.com/verademo/security-ci-includes/-/blob/master/sca-scan.yml'
   
image: maven:3.6-jdk-11

cache:
    key: "$CI_JOB_NAME"
    paths:
        - .m2/repository

package:
    stage: package
    script:
        - 'mvn $MAVEN_CLI_OPTS package'
    artifacts:
        paths:
            - target

sca-scan:
    stage: security
    extends: .sca-scan
    
sast-pipeline-scan:
    stage: security
    extends: .sast-pipeline-scan
    except:
        - master
    variables:
        VERACODE_FILEPATH: 'target/demo-*.war'


development-upload-for-sast:
    stage: scan
    only:
        - development
    script:
        - java -jar $HOME/helpers/VeracodeJavaAPI.jar -vid ${VERACODE_API_KEY_ID} -vkey ${VERACODE_API_KEY_SECRET}
          -action UploadAndScan -appname "${VERACODE_APPLICATION}" -createprofile false -autoscan true -sandboxname "gitlab-development"
          -filepath ./target/verademo.war -version "Job ${CI_JOB_ID} in pipeline ${CI_PIPELINE_ID}"
    allow_failure: true
    
release-upload-for-sast:
    stage: scan
    only:
        - release
    script:
        - java -jar $HOME/helpers/VeracodeJavaAPI.jar -vid ${VERACODE_API_KEY_ID} -vkey ${VERACODE_API_KEY_SECRET}
          -action UploadAndScan -appname "${VERACODE_APPLICATION}" -createprofile false -autoscan true -sandboxname "gitlab-release"
          -filepath ./target/verademo.war -version "Job ${CI_JOB_ID} in pipeline ${CI_PIPELINE_ID}"
    allow_failure: true
    
policy-upload-for-sast:
    stage: scan
    only:
        - schedules
        - master
    script:
        - java -jar $HOME/helpers/VeracodeJavaAPI.jar -vid ${VERACODE_API_KEY_ID} -vkey ${VERACODE_API_KEY_SECRET}
          -action UploadAndScan -appname "${VERACODE_APPLICATION}" -createprofile false -autoscan true
          -filepath ./target/verademo.war -version "Job ${CI_JOB_ID} in pipeline ${CI_PIPELINE_ID}"
          -scantimeout 15
